### ISSUE TITLE
Update on CF?

### ISSUE THREAD

**Issue by gamerpotion** [devOS-Sanity-Edition/TeaBridge#15]
Hi this is not an issue but did not see another place to contact on.
Just wondering if you had any plans to upload this to CurseForge? so I could use it with my modpack - https://www.curseforge.com/minecraft/modpacks/darkrpg

also just to confirm that ```@everyone``` is disabled?

Thanks

**Comment by asoji** [comment]
- We don't plan on uploading any of our mods to CurseForge, but if you're able to add a manual override somehow, feel free to!
- Pinging `@everyone` and `@here` shouldn't be possible [mention filtering]
