### ISSUE TITLE
webhooks can use @everyone

### ISSUE THREAD

**Issue by LemmaEOF** [devOS-Sanity-Edition/TeaBridge#18]
![Capto_Capture 2023-08-22_12-33-08_AM](https://github.com/devOS-Sanity-Edition/TeaBridge/assets/6722691/f5a44ada-d68e-4b93-9c7f-8986a9c681cf)

**Comment by asoji** [comment]
Crap, I was just about to make an issue on this, I could've sworn mention filtering worked in previous builds, so something just broke recently...

**Comment by maximumpower55** [comment]
Fixed in 1.2.3 https://modrinth.com/mod/teabridge/version/1.2.3
