### ISSUE TITLE
Strange error when bot is missing intent

### ISSUE THREAD

**Issue by comp500** [devOS-Sanity-Edition/TeaBridge#19]
When the bot is missing the message content intent, you get an error that doesn't make sense: `Failed to send webhook message to discord : 
java.lang.NullPointerException: Cannot invoke "net.dv8tion.jda.api.entities.Guild.getSelfMember()" because the return value of "net.dv8tion.jda.api.JDA.getGuildById(long)" is null`

Log: [2023-08-25-3.log](https://github.com/devOS-Sanity-Edition/TeaBridge/files/12439422/2023-08-25-3.log)

I'm not sure if there's a way of determining when this intent is missing, but if there is it'd be nice to have a more comprehensible error :)

**Comment by maximumpower55** [comment]
Fixed in the next release, with a new error message along the lines of "Guild is null. This most likely means you are missing the message content intent, please enable it within the app's settings in the discord developer portal."
