### ISSUE TITLE
error in console when someone joins the discord server

### ISSUE THREAD

**Issue by Un1q32** [devOS-Sanity-Edition/TeaBridge#21]
If join messages are printed in the same channel as chat, then this gets printed in console when someone joins the discord

<img width="735" alt="Screenshot 2024-05-29 at 1 59 06 PM" src="https://github.com/devOS-Sanity-Edition/TeaBridge/assets/57970114/c6d554ef-a76b-49c1-87d0-c045c3368f2e">

**Comment by maximumpower55** [comment]
Pending release
