### ISSUE TITLE
Proximity Chat Discord-Minecraf

### ISSUE THREAD

**Issue by ExplosiveGeek77** [devOS-Sanity-Edition/TeaBridge#23]
I can't tell you the exact way to add this functionality, but I want you to add the ability to join a VC and you can talk to people in game, when you walk away they will get quieter and closer it gets louder. AKA, full 3D audio/positional audio.

https://modrinth.com/plugin/simple-voice-chat with https://modrinth.com/plugin/simple-voice-chat-discord-bridge, https://modrinth.com/mod/discord-proximity. I don't know if plugins will be particularly helpful for you but https://www.spigotmc.org/resources/discordsrv.18494/ does this and https://www.spigotmc.org/resources/skoice-proximity-voice-chat.82861/ also does this, and it does it really well. These are the only ones I could find right now. All these options can do what I want but the problem is many of them aren't updated to 1.20.6, which is what my server runs on, and discordsrv and skoice both don't have positional/3D audio support. I also like you discord integration a lot so I am interested in this feature among the others.

**Comment by maximumpower55** [comment]
Not really within scope, also way too complex for me
