### ISSUE TITLE
PluralKit Support

### ISSUE THREAD

**Issue by Oliver-makes-code** [devOS-Sanity-Edition/TeaBridge#7]
It'd be neat if there was PluralKit support.
You can detect messages sent by PluralKit and relay them to Minecraft using PlruralKit's API (Documentation found here: https://pluralkit.me/api/)

**Comment by maximumpower55** [comment]
I will look into this for v1.1.0

**Comment by maximumpower55** [comment]
@Oliver-makes-code I have been able to make it so messages from PK webhooks are actually sent, but I haven't figured out how to not send the messages that are about to be proxied

**Comment by Oliver-makes-code** [comment]
You can make a lookup to PK's API with the old message id and it'll return a valid message object if it was proxied

**Comment by maximumpower55** [comment]
> You can make a lookup to PK's API with the old message id and it'll return a valid message object if it was proxied

The problem is the `MessageReceivedEvent` is invoked before the message is proxied

**Comment by maximumpower55** [comment]
The only way I know of fixing this is somehow delaying the event until the message is proxied, and that's jank since that will add delay to normal messages

**Comment by maximumpower55** [comment]
Forgot to close this earlier, this is now done.
